// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goframe-shop-v2/internal/dao/internal"
)

// internalSeckillActivityDao is an internal type for wrapping the internal DAO implementation.
type internalSeckillActivityDao = *internal.SeckillActivityDao

// seckillActivityDao is the data access object for the table seckill_activity.
// You can define custom methods on it to extend its functionality as needed.
type seckillActivityDao struct {
	internalSeckillActivityDao
}

var (
	// SeckillActivity is a globally accessible object for table seckill_activity operations.
	SeckillActivity = seckillActivityDao{
		internal.NewSeckillActivityDao(),
	}
)

// Add your custom methods and functionality below.
