// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goframe-shop-v2/internal/dao/internal"
)

// internalUntitledTable24Dao is an internal type for wrapping the internal DAO implementation.
type internalUntitledTable24Dao = *internal.UntitledTable24Dao

// untitledTable24Dao is the data access object for the table untitled_table_24.
// You can define custom methods on it to extend its functionality as needed.
type untitledTable24Dao struct {
	internalUntitledTable24Dao
}

var (
	// UntitledTable24 is a globally accessible object for table untitled_table_24 operations.
	UntitledTable24 = untitledTable24Dao{
		internal.NewUntitledTable24Dao(),
	}
)

// Add your custom methods and functionality below.
